
" Why download a plugin manager when I can do it manually?
" (I'm too lazy to try to figure out how plugin managers work with git
" submodules)
filetype plugin on
" Load the plugins...


execute "source " . $HOME . "/.vim/SimplePlug.vim"

" lervag/vimtex
Plugin "vimtex"
Plugin "SimpylFold"
" scrooloose/nerdtree
"Plugin "nerdtree"
" tmux-plugins/vim-tmux-focus-events
Plugin "vim-tmux-focus-events"
" Easy Align
Plugin "vim-easy-align"

"Jinja syntax highlighting
Plugin "Vim-Jinja2-Syntax"


" And of course, my awesome plugin...
Plugin "personal"

" You complete me has to be loaded after personal since
" personal changes it's settings
Plugin "YouCompleteMe"


"Plug 'octol/vim-cpp-enhanced-highlight' 		                                " cpp syntax highlighting
"Plug 'justinmk/vim-syntax-extra'
""Plug 'Valloric/YouCompleteMe'                                                  " YCM -- to complicated
"Plug 'vim-scripts/Align'                                                        " Align stuff
"Plug 'matze/vim-move'                                                           " Move code around
